### ISSUE TITLE
Finish basic work on event participants

### ISSUE THREAD

**Issue by mrkvon** [hnuti-brontosaurus/bis-frontend#119]
@regenerativecommunity 

- [ ] Export pdf with attendance-list (Talita)
- [x] Delete application correctly (Talita)
- [ ] Handling errors while adding a participant ()
- [ ] Mobile view (Talita)
- [x] Create new user as participant (Michal) #127 
- [x] Update participant (Michal) #129 
- [x] Delete participant (Michal) #128 
- [x] Follow-up of #127, #128, #129 - make better UX for it (show that something is happening when saving data, keep editing when api fails)

- (maybe) Import participants from xls
- (maybe) bulk actions - applications - Delete many applications, add many participants at once.
